import React, { useState, useEffect } from 'react';
import { Bot, MessageSquare, Calendar, TrendingUp, Clock, Activity } from 'lucide-react';
import { Card } from '../ui';
import { LandingPageAPI } from '../../services/landingPageApi';

interface AgentActivity {
  time: string;
  action: string;
  type: string;
}

interface AgentStats {
  ai_generated_posts: number;
  ai_engagements: number;
  ai_followups: number;
  ai_booked_demos: number;
  last_post_time: string;
  last_activity: string;
  is_live: boolean;
  status: string;
  response_time_avg: string;
  live_activities: AgentActivity[];
}

const MetaProofSection: React.FC = () => {
  const [agentStats, setAgentStats] = useState<AgentStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAgentStats = async () => {
      try {
        const stats = await LandingPageAPI.getAgentActivityStats();
        setAgentStats(stats);
      } catch (err) {
        console.error('Failed to fetch agent stats:', err);
        setError('Unable to load agent activity data');
      } finally {
        setLoading(false);
      }
    };

    fetchAgentStats();

    // Refresh stats every 30 seconds
    const interval = setInterval(fetchAgentStats, 30000);
    return () => clearInterval(interval);
  }, []);

  const ActivityCard: React.FC<{
    icon: React.ReactNode;
    stat: number | string;
    label: string;
    sublabel: string;
  }> = ({ icon, stat, label, sublabel }) => (
    <Card className="p-4 text-center bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200">
      <div className="flex items-center justify-center mb-2">
        <div className="p-2 bg-blue-100 rounded-full mr-3">
          {icon}
        </div>
        <div className="text-left">
          <div className="text-2xl font-bold text-blue-600">{stat}</div>
          <div className="text-sm text-blue-700 font-medium">{label}</div>
          <div className="text-xs text-blue-500">{sublabel}</div>
        </div>
      </div>
    </Card>
  );

  if (loading) {
    return (
      <section id="meta-proof" className="py-20 bg-gradient-to-br from-slate-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="animate-pulse">
            <div className="h-8 bg-gray-300 rounded w-1/3 mx-auto mb-8"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
              {[...Array(4)].map((_, i) => (
                <div key={i} className="h-24 bg-gray-300 rounded"></div>
              ))}
            </div>
          </div>
        </div>
      </section>
    );
  }

  if (error || !agentStats) {
    return (
      <section id="meta-proof" className="py-20 bg-gradient-to-br from-slate-50 to-blue-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
            <p className="text-yellow-800">Agent activity dashboard temporarily unavailable</p>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="meta-proof" className="py-20 bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center bg-green-100 text-green-800 px-4 py-2 rounded-full text-sm font-medium mb-6">
            <Activity className="w-4 h-4 mr-2" />
            🔴 LIVE - Agent Active
          </div>
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            🤖 This Website is Being Marketed by Unitasa's Own AI Agent
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            We eat our own dog food. Real-time results from our AI marketing agent that's actively working to grow Unitasa.
          </p>
        </div>

        {/* Agent Activity Dashboard */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <ActivityCard
            icon={<Bot className="w-5 h-5 text-blue-600" />}
            stat={agentStats.ai_generated_posts}
            label="LinkedIn posts generated by AI"
            sublabel={`Last: ${agentStats.last_post_time}`}
          />
          <ActivityCard
            icon={<MessageSquare className="w-5 h-5 text-green-600" />}
            stat={agentStats.ai_engagements}
            label="Automated engagements"
            sublabel="All personalized by AI"
          />
          <ActivityCard
            icon={<Clock className="w-5 h-5 text-orange-600" />}
            stat={agentStats.ai_followups}
            label="Assessment follow-ups"
            sublabel={agentStats.response_time_avg}
          />
          <ActivityCard
            icon={<Calendar className="w-5 h-5 text-purple-600" />}
            stat={agentStats.ai_booked_demos}
            label="Demos booked by agent"
            sublabel="Zero manual work"
          />
        </div>

        {/* Proof Statement */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-12">
          <div className="text-center">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              This isn't a demo. This is the product, marketing itself.
            </h3>
            <p className="text-lg text-gray-600 mb-6">
              The same AI agent that powers this website will power your marketing automation.
              Every post, engagement, and follow-up you see above was generated and executed by our AI system.
            </p>
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4">
              <p className="text-sm text-gray-700">
                <strong>Last updated:</strong> {new Date(agentStats.last_activity).toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        {/* Live Activity Feed */}
        <Card className="p-6">
          <h3 className="text-xl font-bold text-gray-900 mb-6 flex items-center">
            <Activity className="w-5 h-5 mr-2 text-green-600" />
            🔴 Live Agent Activity Feed
          </h3>

          <div className="space-y-4">
            {agentStats.live_activities && agentStats.live_activities.length > 0 ? (
              agentStats.live_activities.map((activity, index) => (
                <div key={index} className="flex items-start space-x-4 p-4 bg-gray-50 rounded-lg">
                  <div className="flex-shrink-0">
                    <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center">
                      <Bot className="w-4 h-4 text-blue-600" />
                    </div>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <span className="text-sm font-medium text-gray-900">{activity.time}</span>
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        activity.type === 'content_creation' ? 'bg-blue-100 text-blue-800' :
                        activity.type === 'engagement' ? 'bg-green-100 text-green-800' :
                        'bg-purple-100 text-purple-800'
                      }`}>
                        {activity.type.replace('_', ' ')}
                      </span>
                    </div>
                    <p className="text-sm text-gray-700">{activity.action}</p>
                  </div>
                </div>
              ))
            ) : (
              <div className="text-center py-8 text-gray-500">
                <Bot className="w-12 h-12 mx-auto mb-4 text-gray-300" />
                <p>No recent agent activities to display</p>
                <p className="text-sm mt-2">Activities will appear here as the AI agent works</p>
              </div>
            )}
          </div>

          <div className="mt-6 text-center">
            <button className="text-blue-600 hover:text-blue-800 text-sm font-medium">
              View full agent dashboard →
            </button>
          </div>
        </Card>
      </div>
    </section>
  );
};

export default MetaProofSection;